version: "3.9"

services:
  core:
    stdin_open: true
    tty: true
    container_name: core_container
    build: .
    command: server /export
    env_file:
      - .env
    volumes:
      - ./:/src
    expose:
      - 8000
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db_container
    image: postgres:9.6.16
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing321
      - POSTGRES_DB=mydb
    volumes:
      - ./database:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    build:
      context: .
    command: celery -A app worker -l info
    depends_on:
      - db
      - redis
      - app

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
      - core
    ports:
      - 8000:8000

volumes:
  db_data: