version: "3.9"

services:
  db:
    image: postgres:13.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing321
      - POSTGRES_DB=mydb
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  celery:
    build:
      context: .
    env_file:
      - .env
    command: celery -A HtmlAnalyzer.celery:app worker -l info
    depends_on:
      - db
      - redis
      - app

  app:
    build: .
    command: sh /usr/src/app/entrypoint.sh
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    ports:
      - 8000:8000

volumes:
  db_data:
