# Generated by Django 3.2.3 on 2021-05-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='Url')),
                ('identifier', models.CharField(max_length=8, unique=True, verbose_name='Task identifier')),
                ('analyzed_data', models.JSONField(blank=True, default=dict, verbose_name='Analyzed data')),
            ],
        ),
    ]
